### ISSUE TITLE
Sync channels more promptly

### ISSUE THREAD

**Issue by kauffj** [lbryio/ytsync#50] opened 2019-12-17 15:25 UTC
At least for popular channels (either by YT status, IAPI subs, or both)

**Comment by nikooo777** [comment] 2019-12-17 15:31
duplicate of https://github.com/lbryio/ytsync/issues/44 and possibly https://github.com/lbryio/lbry-desktop/issues/3284#issuecomment-558335852

**Closed by nikooo777** 2019-12-17 15:31 UTC
Labels: consider soon
